version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cimg/node:22.9.0

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-v2-{{ .Branch }}
            - yarn-v2
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: yarn-v2-{{ .Branch }}-{{ epoch }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run linters
          command: |
            yarn lint

  build-publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
      - restore_cache:
          keys:
            - docker-v1-{{ .Branch }}
            - docker-v1
      - run:
          name: Load Docker cache
          command: |
            docker load -i ~/cache/docker.tar || true
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from=cache -t ghcr.io/markormesher/iperf-prometheus-collector:$(git describe) .
            docker image ls
      - run:
          name: Maybe publish Docker image
          command: |
            # publish tagged commits only
            if ! git describe --exact-match HEAD > /dev/null 2>&1; then echo "Not on tagged commit - nothing to do"; exit 0; fi
            echo "${GHCR_PUBLISH_TOKEN}" | docker login ghcr.io -u markormesher --password-stdin
            docker push ghcr.io/markormesher/iperf-prometheus-collector:$(git describe)
      - run:
          name: Create Docker cache
          command: |
            rm -rf ~/cache
            mkdir ~/cache
            docker tag ghcr.io/markormesher/iperf-prometheus-collector:$(git describe) cache
            docker save -o ~/cache/docker.tar cache
            ls -lh ~/cache/docker.tar
      - save_cache:
          key: docker-v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/cache

workflows:
  version: 2
  main:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build-publish:
          requires:
            - lint
